apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-postgres-332488
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar-postgres-332488
  template:
    metadata:
      name: sonar-postgres-332488
      labels:
        app: sonar-postgres-332488
    spec:
      containers:
      - image: postgres:9.6
        imagePullPolicy: IfNotPresent
        name: sonar-postgres-332488
        env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: sonar
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: postgresport

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: sonar-postgres-332488
  name: sonar-postgres-332488
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: sonar-postgres-port
  selector:
    app: sonar-postgres-332488
